### ISSUE TITLE
The pre-extracted features and targets of TVSeries 

### ISSUE THREAD

**Issue by sw1014** [jbistanbul/MiniROAD#1]
Could you please give me some guidance on how to download the pre-extracted features and targets of TVSeries? I can't find it in TeSTra.

**Comment by jbistanbul** [comment]
I followed LSTR (https://github.com/amazon-science/long-short-term-transformer).
You need to first download the TVSeries dataset (RGB video) and then follow the procedures explained in LSTR.
Issues raised in LSTR (ex. https://github.com/amazon-science/long-short-term-transformer/issues/2) helped.

**Comment by sw1014** [comment]
OK, I will follow your advice, thank you very much for your helpful response!
