### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by chcchc97** [jbistanbul/MiniROAD#2]
I have another question about the feature extraction. Because I want to apply MiniROAD to other datasets, so I try to extract the features by myself. As section 4 Implementation details in the supplementary of the paper, "For THUMOS and TVSeries,
we first sample the videos into 24 FPS and feed nonoverlapping snippets to the feature extractor. The snippet size is set to 6 and TSN is adopted as the feature extractor. " I have resample the videos at 24 FPS and extract RGB and flow(视频帧和光流) using [mmaction2](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/README.md) But I don't know how to set the video snippet size to 6. How could you do that and are there any tools in mmaction2 can help to realize this step?

**Comment by jbistanbul** [comment]
Thanks for your interest in our work. 
For extracting the RGB feature, it means that for every chunk (6 frames), you extract one RGB feature. Since the paper used TSN as the backbone, I followed previous works where the middle frame (4th frame) was input to the TSN to extract RGB features (as TSN R50 backbone for RGB inputs only a single frame).
For extracting the FLOW feature, the flow of the chunk (6 frames) should first be extracted which results in 10 flows (x,y,x,y,x,y,x,y,x,y). These (x,y,x,y,x,y,x,y,x,y) should then be concatenated and input to the flow-specific model (InceptionNet, R50, or whatever you want to use). 
I followed LSTR (https://github.com/amazon-science/long-short-term-transformer#data-preparation) for details where issues raised in that repo like https://github.com/amazon-science/long-short-term-transformer/issues/2 helped.

**Comment by chcchc97** [comment]
Thank you for your reply!
For extracting the RGB feature, as this link say[https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/README.md](url), I extract RGB with [build_rawframes.py](https://github.com/open-mmlab/mmaction2/blob/4d6c93474730cad2f25e51109adcf96824efc7a3/tools/data/build_rawframes.py#L4) and then extract the RGB feature with [clip_feature_extraction.py](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/README.md). But it extract the RGB feature for every frame, I don't know how to use the mmaction2 tools extract the RGB feature for 6 frames. So do you use the MMaction2 tool to realize the step of extracting one RGB feature for every chunk (6 frames) ? If so, could you share me about how to use them?

**Comment by jbistanbul** [comment]
I did not utilize the MMaction2 tool for feature extraction; instead, I employed its checkpoints solely for initializing the model, while the remainder of the process was conducted using custom-built codes. Nonetheless, if the tool you're using extracts a single feature per frame, a viable approach might be to select every fourth feature out of every six. This method should yield an equivalent result.

**Comment by chcchc97** [comment]
It's very kind of you!
I have another question. In your readme, You have mentioned that  I can also directly download the pre-extracted features and targets from [TeSTra](https://github.com/zhaoyue-zephyrus/TeSTra). I have problem about the shape of the features. I download [THUMOS'14 Flow (TV-L1) feature](https://utexas.app.box.com/s/rhvihb33e54ro07zsmcbgku16cikk2g4) but the side is 2048 not 1024. Are there something wrong about the flow feature？Did you use the flow features in [TeSTra](https://github.com/zhaoyue-zephyrus/TeSTra). I put the video_test_0000004 as the example as follow. If you didn't use these flow features, could you share the flow features with me？ Thank you very much！
![image](https://github.com/jbistanbul/MiniROAD/assets/60684460/ddc9db96-ba43-44c3-a8a8-5108a6b6fa4e)

**Comment by jbistanbul** [comment]
Yes, we have utilized features from TeSTra for the datasets we have access to. The feature dimensions can vary based on the chosen backbone architecture of the flow model. For instance, using the backbone from this version of bninception (see https://github.com/amazon-science/long-short-term-transformer/issues/19) results in a dimension of 1024. On the other hand, the weights available in MMaction, which as far as I recall were based on Res50, produce a dimension of 2048. Depending on the backbone you select, you can adjust the dimension accordingly to either 1024 or 2048, or another value if you opt for a different architecture.

**Comment by chcchc97** [comment]
I've got it, thanks for the detailed answer, and a happy new year to you!
